### ISSUE TITLE
No distribution of messages if there is multiple instances of redis verticle

### ISSUE THREAD

**Issue by abhi4578** [datakaveri/latest-ingestion-pipeline#6]
This is due to fact that all redis verticle would subscribe the same eventbus address and will get all the messages.

Possible solutions from discussion with @kailash 
1. either to use a service proxy model
2. push processed messages to rabbitmq back and then let redis consume back from there, implying the multiple consumers from rmq queue will be round robin - leading to distribution of messages.

@swaminathanvasanth cc

**Comment by kailash** [comment]
GIS Server is migrated to service proxy model.
